name: my-app-development
run-name: built by ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: install dependencies
        run: npm ci
      - name: building
        run: npm run build
      - name: List files in the repository
        run: ls ${{ github.workspace }}
